2018-11-28 19:30:42,513 [ERROR @ base_events.py:default_exception_handler:1265] 3963 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-11-28 19:30:42,515 [ERROR @ base_events.py:default_exception_handler:1265] 3963 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-11-28 19:30:42,516 [ERROR @ base_events.py:default_exception_handler:1265] 3963 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-11-28 19:30:42,519 [ERROR @ base_events.py:default_exception_handler:1265] 3963 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/Users/akiyoshi/.pyenv/versions/neovim3/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
